const STORE_USER_ACTION = "STORE_USER_ACTION";
const STORE_TOKEN_ACTION = "STORE_TOKEN_ACTION";
const DELETE_TOKEN_ACTION = "DELETE_TOKEN_ACTION";
const DELETE_USER_ACTION = "DELETE_USER_ACTION";

export {
  STORE_USER_ACTION,
  DELETE_USER_ACTION,
  STORE_TOKEN_ACTION,
  DELETE_TOKEN_ACTION,
};
